config/routes.rb
Rails.application.routes.draw do
    resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :content, length:{ minimum:1, maximum:140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    # Contact.create(name: params["name"],email: params["email"], content: params["content"])
    Contact.create(params.permit(:name,:email,:content))
    redirect_to new_contact_path
  end
  
  private
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<%= form_with(modle: @contact, local: true, url: contacts_path) do |form| %>
    <div class="contact_name">
        <%=  form.label :name%>
        <%=  form.text_field :name%>
    </div>
    <div class="contact_email">
        <%=  form.label :email%>
        <%=  form.text_field :email%>
    </div>
    <div class="contact_content">
        <%=  form.label :content%>
        <%=  form.text_field :content%>        
    </div>
    <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DicTaskContact</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>